### ISSUE TITLE
Ensure all files include license headers

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#168]
For legal reasons we need to include the license in every file that we consider "Source Code". 

Should we have a CI/CD check for this or any easy `make` target we can run to check/append files as needed?

**Comment by dmah42** [comment]
http://www.apache.org/dev/apply-license.html#copy-per-file

"DO I HAVE TO HAVE A COPY OF THE LICENSE IN EACH SOURCE FILE?

Only one full copy of the license is needed per distribution. See the policy."

I don't think we need to.  if you want to that's fine, but Apache specifically doesn't require it (unlike more restrictive licenses).

**Comment by future-highway** [comment]
Don't know what the decision is going to be here, but since I have probably forgotten on 98% of the files I created, I went ahead and set clion to include the header on new rust files. Instructions for those interested:

1. Open Settings
2. Go to Editor -> File and Code Templates
3. Change Scheme to Project
4. In each file type expected to be used (e.g., Rust, Typescript), paste the header in the box.
5. Hit apply

I feel like there should be a way to add it on auto-format. I'll update if I find it.
