### ISSUE TITLE
Formalize Nivenly Foundation

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#387]
We need to do a few things to solidify our relationship with Nivenly

 - [x] Adopt the Nivenly covenant/code of conduct
 - [ ] Adopt the Nivenly CLA
 - [x] Add a small logo/language to the README

**Comment by dmah42** [comment]
i haven't figured out how to link to the Nivenly CLA.  @quintessence is that something you know how to do?

**Comment by dmah42** [comment]
chatted offline with the Nivenly folks and we don't have to adopt the Nivenly CLA if we have one then works.  and getting everyone to resign/reapprove a new CLA even if it's identical would be painful.

as such I think we can stick with the Aurae CLA.

if anyone has a stronger opinion please shout, but for now I'm marking this as complete.

(I think we might migrate the cla bot from kube to Aurae though so that's kinda neat....)
