### ISSUE TITLE
Break the build on compile warnings

### ISSUE THREAD

**Issue by krisnova** [aurae-runtime/aurae#54]
Can we please break the build and fail a pull request if code creates a rust warning? 

We are trying to keep a clean set of code for the project, and we would like to leverage the Makefile commands to ensure that no warnings are generated. 

This includes 

 - Documentation
 - Linting
 - Unused (dead) code
 - etc

**Comment by dominichamon** [comment]
i'll start on this to get a feel for the code if you want

**Comment by future-highway** [comment]
Thinking about the approach to this, I'm not sure about using `deny` to fail the build. It makes it more difficult to differentiate normal errors from lint based ones. I'm also concerned about discouraging contributions since not everyone is fully comfortable with rust yet.

An alternate approach is to use `warn` for any lints we want (that are default-allow). Then, we can alter the `cargo clippy` to `cargo clippy -- -D warnings` in the GitHub checks. The hope is that we don't discourage contributors from opening a PR, where those who need it can get a review/help in fixing the warnings.

**Comment by dominichamon** [comment]
ok, that's fair. i think we'd also want to add this to the `Makefile`, not just the github checks.

i can start by adding the warnings to the Makefile and fixing anything, then we can audit any default-allow warnings we want to add?

**Comment by future-highway** [comment]
I'm fine with whatever the decision is, but the reason I didn't want to suggest adding it to the makefile was to let people open PR's with the warnings. `cargo clippy -- -D warnings` will make all the warnings show as errors. 

Maybe we can have an additional makefile command that is strict and people could be encouraged to run it prior to the PR, but wouldn't be part of the normal dev flow.

**Comment by bpmooch** [comment]
at work we have below and it works pretty good

```
install: deps
	@cargo install --path .

## Lint code
lint: deps
	@rustup component add clippy 2> /dev/null
	@cargo clippy --all-features --all -- -D clippy::all -D warnings
```

**Comment by dmah42** [comment]
i think it's ok to close this. we have some more to enable but it doesn't need an issue to track :)
